@baseUrl = http://localhost:5200
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withcredentials: true

{
  "userTo": "651c3adce69a6749489afc0f",
  "postId": "652eaf56b2eb82bb4ace4fe4",
  "comment": "This is second comment",
  "profilePicture": "https://res.cloudinary.com/deghbmw6y/image/upload/v1695484427/650f0a06e5a3fc10c197a714"
}


###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/652eaf56b2eb82bb4ace4fe4
Content-Type: application/json
Accept: application/json
withcredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/652eaf56b2eb82bb4ace4fe4/6536997008ba5d9864793c31
Content-Type: application/json
Accept: application/json
withcredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/comments/652eaf56b2eb82bb4ace4fe4
Content-Type: application/json
Accept: application/json
withcredentials: true

